### ISSUE TITLE
Continuous socket hang-up when posting requests

### ISSUE THREAD

**Issue by Schachte** [probot/smee#51]
@bkeepers Having some issues with smee and simulating webhooks. 

I'm grabbing the payload data from the app settings page with the correct headers and payload and issuing a post through Postman. 

When I issue a request locally through smee, I get a socket hang-up error.

I can reissue the requests from GitHub and it seems to hit my localserver correctly, otherwise, no dice in something like Postman. 

```
04:51:34.324Z ERROR probot: socket hang up
  Error: socket hang up
      at createHangUpError (_http_client.js:331:15)
      at Socket.socketOnEnd (_http_client.js:423:23)
      at emitNone (events.js:111:20)
      at Socket.emit (events.js:208:7)
      at endReadableNT (_stream_readable.js:1055:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by bkeepers** [comment]
@Schachte can you share a curl request that Postman is making that causes the error?

**Comment by Schachte** [comment]
@bkeepers I ended up switching over to execution via the GitHub settings page to re-execute. Playing around a bit more, once I got an official request made, re-creating the request in the smee web-client seems to be working as expected. Thanks!
