### ISSUE TITLE
Bad Request Error 

### ISSUE THREAD

**Issue by ani6gup** [probot/smee#63]
👋 Hi! I was working with @hiimbex on building a GitHub app for the first time using Probot. We ended up coming across this error. 

Creating a new smee channel ended up solving the error but wanted to put this up to see what happened.

```3:11:04.434Z ERROR probot: Bad Request
  Error: Bad Request
      at Request.callback (/Users/ani6gup/Desktop/my-first-app/node_modules/superagent/lib/node/index.js:706:15)
      at IncomingMessage.parser (/Users/ani6gup/Desktop/my-first-app/node_modules/superagent/lib/node/index.js:916:18)
      at emitNone (events.js:110:20)
      at IncomingMessage.emit (events.js:207:7)
      at endReadableNT (_stream_readable.js:1057:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by JasonEtco** [comment]
Hm weird 🤔 We don't have any logging set up for Smee (we really should) so unfortunately I can't take a look there.

I haven't seen this error before and it doesn't seem to include any useful information. Taking a look at Heroku it says that there have been a few "critical" errors in the last 24 hours, but since we don't have log storage/management I can't dig in any further.

I'm going to close this since we don't have any more information at this time, but if you see it again maybe ping me on Slack so I can take a look 🙏
