### ISSUE TITLE
Failing to run after installing

### ISSUE THREAD

**Issue by BasThomas** [probot/smee#69]
I installed `smee`:

```
$ npm install --global smee-client
```

Now running anything (eg. `smee --help` or `smee -u <url>`) fails, with the following error:

```
/usr/local/lib/node_modules/smee-client/bin/smee.js:16
async function setup () {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
```

**Comment by BasThomas** [comment]
After updating `npm`, it now works.

**Comment by sangshuduo** [comment]
still happen with npm 3.5.2 / node 4.2.6 :(

**Comment by smartITNinja** [comment]
It works OK with 
# npm --version
6.14.12
