### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by tommytang1995** [probot/smee#97]
Hi guys,
I got this issue while connecting to the smee. I was able to receive the event on the smee website but the payload was not sent to my local machine. Instead, I got this message down below:

```
$ smee --url <the url> --path /event_handler --port 3000  Forwarding <the url> to http://127.0.0.1:3000C:/Program F iles/Git/event_handler                                                           
Connected <the url>                                      
 { Error: connect ECONNREFUSED 127.0.0.1:80                                           
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)                
errno: 'ECONNREFUSED',                                                           
code: 'ECONNREFUSED',                                                            
syscall: 'connect',                                                              
address: '127.0.0.1',                                                            
port: 80,                                                                        
response: undefined }                                                          
{ Error: connect ECONNREFUSED 127.0.0.1:80                                           
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)
errno: 'ECONNREFUSED',                                                           
code: 'ECONNREFUSED',                                                            
syscall: 'connect',                                                              
address: '127.0.0.1',                                                           
port: 80,                                                                       
response: undefined }
```

**Comment by ritesh-singh** [comment]
Hey @tommytang1995  - I am facing same issue, any leads on how you got it resolved?
